### ISSUE TITLE
sage/utils/imports.py: TypeError reload() takes exactly one argument (4 given)

### ISSUE THREAD

**Issue by pshahid** [spicerack/sage#24]
Error encountered on master:
```
2016-03-05 16:59:36:689993 [-]     module = _imp.reload(mod_name, *tup)
2016-03-05 16:59:36:690067 [-] TypeError: reload() takes exactly one argument (4 given)
```
sage/utils/imports.py line 93 changed from
`module = _imp.load_module(mod_name, *tup)` to `module = _imp.reload...` . 

Reload doesn't appear to be an attribute of that module, yet it doesn't throw an attribute error. Furthermore, I'm not quite sure the motivation behind changing from imp.load_module to imp.reload as the documentation indicates that the builtin reload() and imp.load_module are equivalent in the case that a module object is already loaded.

Finally, this behavior could be improved by adding a try...finally, as the documentation also indicates that the caller of load_module must close the file descriptor explicitly. So, we need to undo what was committed in 1ea518 and add a try...finally.

Ironically, the commit this change was introduced was 1ea518, which expressed a lack of testing :D

**Comment by jaiko** [comment]
My bad. Sage apps needs a rewrite. I did it wrong :(.
