### ISSUE TITLE
Is there a way to send GMCP commands?

### ISSUE THREAD

**Issue by adayoung** [spicerack/sage#29]
Hi! I've been using sage as a proxy between Achaea and Mudlet and I haven't quite figured out how to send GMCP commands when I'm connected through sage. IRE games usually support [GMCP commands](https://nexus.ironrealms.com/GMCP) and it works when I'm connected directly, but not when I'm connected via sage. 

I looked through the various configuration options in sage/defaults.py and ran my toplevel app with `--gmcp-debug` but I could see nothing about why it wouldn't send the supplied GMCP command up to Achaea :frowning_face:

**Comment by adayoung** [comment]
Ohh, I should mention I've been trying to use the [sendGMCP()](https://wiki.mudlet.org/w/Manual:Lua_Functions#sendGMCP) function in Mudlet for this.

**Comment by lorienhu** [comment]
Fixed in 74a1d93
