### ISSUE TITLE
Can we have IAC GA at the end of each prompt written to the client?

### ISSUE THREAD

**Issue by adayoung** [spicerack/sage#30]
Hi! I'm trying to use Mudlet as a client down from sage but it [wants an IAC GA](https://wiki.mudlet.org/w/Listing_Your_MUD) sent after every prompt for an important [API function](https://wiki.mudlet.org/w/Manual:Mudlet_Object_Functions#isPrompt) to work correctly. I was looking through the code and I think something has to be done [here](https://github.com/spicerack/sage/blob/master/sage/net.py#L229) but I couldn't quite figure out what or how.. so umm.. can we please have an IAC GA sent after each prompt for this? XD

**Comment by lorienhu** [comment]
Fixed in ce104c1
